# Generated by Django 2.2.20 on 2021-04-11 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 4, 11, 18, 29, 20, 16847), verbose_name='Опубликована'),
        ),
    ]
